version: "3"

services:
  gateway:
    build:
      context: gateway/docker/nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - ws

  frontend:
    build:
      context: frontend/docker/nginx
    depends_on:
      - frontend-node

  frontend-node:
    build:
      context: frontend/docker/node
    environment:
      PORT: 8080
    volumes:
      - ./frontend:/app
    command: sh -c "until [ -f .is-ready ] ; do sleep 1 ; done && npm run start"
    tty: true

  frontend-cli:
    build:
      context: frontend/docker/node
    volumes:
      - ./frontend:/app

  ws:
    build:
      context: ws/docker/nginx
    depends_on:
      - ws-node

  ws-node:
    build:
      context: ws/docker/node
    volumes:
      - ./ws:/app
    command: sh -c "until [ -f .is-ready ] ; do sleep 1 ; done && npm run start"
    tty: true

  ws-cli:
    build:
      context: ws/docker/node
    volumes:
      - ./ws:/app
